server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  ai:
    zhipuai:
      api-key: ${ZHIPU_KEY}
      base-url: "https://open.bigmodel.cn/api/paas"
      chat:
        options:
          model: glm-4.5